=== crivano/apoia/prompts/sentenca-prev-bi-laudo-favoravel.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "Início_da_Sentença": {
            "type": "object",
            "properties": {
                "APIN": {
                    "type": "boolean"
                },
                "AC25": {
                    "type": "boolean"
                },
                "DM": {
                    "type": "boolean"
                },
                "Revel": {
                    "type": "boolean"
                },
                "Interesse": {
                    "type": "boolean"
                },
                "Prescrição": {
                    "type": "boolean"
                },
                "Ev_Cessação_Benef": {
                    "type": "boolean"
                },
                "Ev_Proposta_Acordo": {
                    "type": "boolean"
                },
                "Ev_Recusa_Acordo": {
                    "type": "boolean"
                },
                "Ev_Impug": {
                    "type": "boolean"
                },
                "Ev_INSS_Impug": {
                    "type": "boolean"
                }
            },
            "required": [
                "APIN",
                "AC25",
                "DM",
                "Revel",
                "Interesse",
                "Prescrição",
                "Ev_Cessação_Benef",
                "Ev_Proposta_Acordo",
                "Ev_Recusa_Acordo",
                "Ev_Impug",
                "Ev_INSS_Impug"
            ]
        },
        "Resultado_do_Laudo": {
            "type": "object",
            "properties": {
                "DtPerícia": {
                    "type": "string"
                },
                "Ev_Laudo": {
                    "type": "integer"
                },
                "ConclusãoPerícia": {
                    "type": "string"
                },
                "PeríodoIncapacidadeAnterior": {
                    "type": "string"
                },
                "Reabilitação": {
                    "type": "string"
                },
                "APIN": {
                    "type": "boolean"
                }
            },
            "required": [
                "DtPerícia",
                "Ev_Laudo",
                "ConclusãoPerícia",
                "PeríodoIncapacidadeAnterior",
                "Reabilitação",
                "APIN"
            ]
        },
        "Qualidade_de_Segurado_pela_DCB": {
            "type": "object",
            "properties": {
                "Ev_Cessação_Benef": {
                    "type": "integer"
                },
                "ÚltimaDCB": {
                    "type": "string"
                },
                "ÚltimaDER_Indef": {
                    "type": "string"
                },
                "DII": {
                    "type": "string"
                },
                "Fonte_QS": {
                    "type": "string"
                }
            },
            "required": [
                "Ev_Cessação_Benef",
                "ÚltimaDCB",
                "ÚltimaDER_Indef",
                "DII",
                "Fonte_QS"
            ]
        },
        "Extração_de_Vínculos_do_CNIS": {
            "type": "object",
            "properties": {
                "Rel_Vínculos": {
                    "type": "string"
                },
                "Dt_Primeiro_Recol": {
                    "type": "string"
                },
                "Dt_Rec_Ant": {
                    "type": "string"
                },
                "Comp_Rec_Ant": {
                    "type": "string"
                },
                "Lista_Comp_Antes_DII_Recol_Depois": {
                    "type": "string"
                },
                "Dt_1o_Recol_pósDII": {
                    "type": "string"
                }
            },
            "required": [
                "Rel_Vínculos",
                "Dt_Primeiro_Recol",
                "Dt_Rec_Ant",
                "Comp_Rec_Ant",
                "Lista_Comp_Antes_DII_Recol_Depois",
                "Dt_1o_Recol_pósDII"
            ]
        },
        "Qualidade_de_Segurado_pelo_CNIS": {
            "type": "object",
            "properties": {
                "Ev_CNIS": {
                    "type": "integer"
                },
                "Ev_Seg_Desemprego": {
                    "type": "integer"
                },
                "Núm_Contrib_Sem_Perder_QS": {
                    "type": "integer"
                },
                "Total_Contrib": {
                    "type": "integer"
                },
                "Dt_Primeiro_Vínculo": {
                    "type": "string"
                },
                "Dt_Primeiro_Recol": {
                    "type": "string"
                },
                "DII": {
                    "type": "string"
                },
                "Comp_DII": {
                    "type": "string"
                },
                "Últ_Comp_Ant_Incapac": {
                    "type": "string"
                },
                "Dt_Recol_Ant_Incapac": {
                    "type": "string"
                },
                "Dt_Ini_Último_Emprego": {
                    "type": "string"
                },
                "Dt_Fim_Último_Emprego": {
                    "type": "string"
                },
                "Últ_Comp_Contrib_Ant": {
                    "type": "string"
                },
                "Espécie_Antes_DII": {
                    "type": "string"
                },
                "Dia_Perda_QS": {
                    "type": "string"
                },
                "Dia_Recupera_QS": {
                    "type": "string"
                },
                "Dt_1o_Recol_pósDII": {
                    "type": "string"
                },
                "Lista_Comp_Antes_DII_Recol_Depois": {
                    "type": "string"
                },
                "Núm_Contrib_Antes_DII": {
                    "type": "integer"
                }
            },
            "required": [
                "Ev_CNIS",
                "Ev_Seg_Desemprego",
                "Núm_Contrib_Sem_Perder_QS",
                "Total_Contrib",
                "Dt_Primeiro_Vínculo",
                "Dt_Primeiro_Recol",
                "DII",
                "Comp_DII",
                "Últ_Comp_Ant_Incapac",
                "Dt_Recol_Ant_Incapac",
                "Dt_Ini_Último_Emprego",
                "Dt_Fim_Último_Emprego",
                "Últ_Comp_Contrib_Ant",
                "Espécie_Antes_DII",
                "Dia_Perda_QS",
                "Dia_Recupera_QS",
                "Dt_1o_Recol_pósDII",
                "Lista_Comp_Antes_DII_Recol_Depois",
                "Núm_Contrib_Antes_DII"
            ]
        },
        "Carência": {
            "type": "object",
            "properties": {
                "Dia_Perda_QS": {
                    "type": "string"
                },
                "Dia_Recupera_QS_Antes_DII": {
                    "type": "string"
                },
                "Dt_1o_Recol_pósDII": {
                    "type": "string"
                },
                "Lista_Comp_Antes_DII_Recol_Depois": {
                    "type": "string"
                },
                "Num_Comp_Antes_DII_Recol_Depois": {
                    "type": "integer"
                },
                "Total_Contrib": {
                    "type": "integer"
                },
                "Núm_Contrib_Antes_DII": {
                    "type": "integer"
                },
                "PatologiaIncapacitante": {
                    "type": "integer"
                },
                "DII": {
                    "type": "string"
                },
                "DID": {
                    "type": "string"
                },
                "Filiação_Oportunista": {
                    "type": "boolean"
                }
            },
            "required": [
                "Dia_Perda_QS",
                "Dia_Recupera_QS_Antes_DII",
                "Dt_1o_Recol_pósDII",
                "Lista_Comp_Antes_DII_Recol_Depois",
                "Num_Comp_Antes_DII_Recol_Depois",
                "Total_Contrib",
                "Núm_Contrib_Antes_DII",
                "PatologiaIncapacitante",
                "DII",
                "DID",
                "Filiação_Oportunista"
            ]
        },
        "Resposta_à_Impugnação_do_INSS_ao_Laudo": {
            "type": "object",
            "properties": {
                "Ev_INSS_Impug": {
                    "type": "integer"
                }
            },
            "required": [
                "Ev_INSS_Impug"
            ]
        },
        "Fechamento_da_Sentença": {
            "type": "object",
            "properties": {
                "Fonte_QS": {
                    "type": "string"
                },
                "Possui_Carência": {
                    "type": "boolean"
                },
                "Espécie_Antes_DII": {
                    "type": "string"
                },
                "DER": {
                    "type": "string"
                },
                "DtPerícia": {
                    "type": "string"
                },
                "Idade": {
                    "type": "integer"
                },
                "ConclusãoPerícia": {
                    "type": "string"
                },
                "DII": {
                    "type": "string"
                },
                "DII_Perm": {
                    "type": "string"
                },
                "DIB": {
                    "type": "string"
                },
                "Concede_Restabelece": {
                    "type": "boolean"
                },
                "Reabilitação": {
                    "type": "boolean"
                },
                "ReabilitaçãoSugerida": {
                    "type": "string"
                },
                "ÚltimaDCB": {
                    "type": "string"
                },
                "DCB": {
                    "type": "string"
                },
                "DCB_90dias_hoje": {
                    "type": "string"
                },
                "DCB_6meses_hoje": {
                    "type": "string"
                },
                "APIN": {
                    "type": "boolean"
                },
                "AC25": {
                    "type": "boolean"
                },
                "Acréscimo25pc": {
                    "type": "boolean"
                },
                "DI_AC25": {
                    "type": "string"
                },
                "DM": {
                    "type": "boolean"
                }
            },
            "required": [
                "Fonte_QS",
                "Possui_Carência",
                "Espécie_Antes_DII",
                "DER",
                "DtPerícia",
                "Idade",
                "ConclusãoPerícia",
                "DII",
                "DII_Perm",
                "DIB",
                "Concede_Restabelece",
                "Reabilitação",
                "ReabilitaçãoSugerida",
                "ÚltimaDCB",
                "DCB",
                "DCB_90dias_hoje",
                "DCB_6meses_hoje",
                "APIN",
                "AC25",
                "Acréscimo25pc",
                "DI_AC25",
                "DM"
            ]
        }
    },
    "required": [
        "Início_da_Sentença",
        "Resultado_do_Laudo",
        "Qualidade_de_Segurado_pela_DCB",
        "Extração_de_Vínculos_do_CNIS",
        "Qualidade_de_Segurado_pelo_CNIS",
        "Carência",
        "Resposta_à_Impugnação_do_INSS_ao_Laudo",
        "Fechamento_da_Sentença"
    ]
}

=== crivano/apoia/prompts/sentenca-prev-bi-laudo-favoravel.json
{
    "Início_da_Sentença": {
        "APIN": false,
        "AC25": false,
        "DM": false,
        "Revel": false,
        "Interesse": false,
        "Prescrição": false,
        "Ev_Cessação_Benef": false,
        "Ev_Proposta_Acordo": false,
        "Ev_Recusa_Acordo": false,
        "Ev_Impug": false,
        "Ev_INSS_Impug": false
    },
    "Resultado_do_Laudo": {
        "DtPerícia": "dd/mm/yyyy",
        "Ev_Laudo": 0,
        "ConclusãoPerícia": "",
        "PeríodoIncapacidadeAnterior": "",
        "Reabilitação": "",
        "APIN": false
    },
    "Qualidade_de_Segurado_pela_DCB": {
        "Ev_Cessação_Benef": 0,
        "ÚltimaDCB": "dd/mm/yyyy",
        "ÚltimaDER_Indef": "dd/mm/yyyy",
        "DII": "dd/mm/yyyy",
        "Fonte_QS": ""
    },
    "Extração_de_Vínculos_do_CNIS": {
        "Rel_Vínculos": "",
        "Dt_Primeiro_Recol": "dd/mm/yyyy",
        "Dt_Rec_Ant": "dd/mm/yyyy",
        "Comp_Rec_Ant": "dd/mm/yyyy",
        "Lista_Comp_Antes_DII_Recol_Depois": "",
        "Dt_1o_Recol_pósDII": "dd/mm/yyyy"
    },
    "Qualidade_de_Segurado_pelo_CNIS": {
        "Ev_CNIS": 0,
        "Ev_Seg_Desemprego": 0,
        "Núm_Contrib_Sem_Perder_QS": 0,
        "Total_Contrib": 0,
        "Dt_Primeiro_Vínculo": "dd/mm/yyyy",
        "Dt_Primeiro_Recol": "dd/mm/yyyy",
        "DII": "dd/mm/yyyy",
        "Comp_DII": "dd/mm/yyyy",
        "Últ_Comp_Ant_Incapac": "dd/mm/yyyy",
        "Dt_Recol_Ant_Incapac": "dd/mm/yyyy",
        "Dt_Ini_Último_Emprego": "dd/mm/yyyy",
        "Dt_Fim_Último_Emprego": "dd/mm/yyyy",
        "Últ_Comp_Contrib_Ant": "dd/mm/yyyy",
        "Espécie_Antes_DII": "",
        "Dia_Perda_QS": "dd/mm/yyyy",
        "Dia_Recupera_QS": "dd/mm/yyyy",
        "Dt_1o_Recol_pósDII": "dd/mm/yyyy",
        "Lista_Comp_Antes_DII_Recol_Depois": "",
        "Núm_Contrib_Antes_DII": 0
    },
    "Carência": {
        "Dia_Perda_QS": "dd/mm/yyyy",
        "Dia_Recupera_QS_Antes_DII": "dd/mm/yyyy",
        "Dt_1o_Recol_pósDII": "dd/mm/yyyy",
        "Lista_Comp_Antes_DII_Recol_Depois": "",
        "Num_Comp_Antes_DII_Recol_Depois": 0,
        "Total_Contrib": 0,
        "Núm_Contrib_Antes_DII": 0,
        "PatologiaIncapacitante": 0,
        "DII": "dd/mm/yyyy",
        "DID": "dd/mm/yyyy",
        "Filiação_Oportunista": false
    },
    "Resposta_à_Impugnação_do_INSS_ao_Laudo": {
        "Ev_INSS_Impug": 0
    },
    "Fechamento_da_Sentença": {
        "Fonte_QS": "",
        "Possui_Carência": false,
        "Espécie_Antes_DII": "",
        "DER": "dd/mm/yyyy",
        "DtPerícia": "dd/mm/yyyy",
        "Idade": 0,
        "ConclusãoPerícia": "",
        "DII": "dd/mm/yyyy",
        "DII_Perm": "dd/mm/yyyy",
        "DIB": "dd/mm/yyyy",
        "Concede_Restabelece": false,
        "Reabilitação": false,
        "ReabilitaçãoSugerida": "",
        "ÚltimaDCB": "dd/mm/yyyy",
        "DCB": "dd/mm/yyyy",
        "DCB_90dias_hoje": "dd/mm/yyyy",
        "DCB_6meses_hoje": "dd/mm/yyyy",
        "APIN": false,
        "AC25": false,
        "Acréscimo25pc": false,
        "DI_AC25": "dd/mm/yyyy",
        "DM": false
    }
}
